name: Générer l'APK Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configuration de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Initialisation du projet Flutter
        run: |
          flutter create . --platforms=android --org=com.cpa.cantine --overwrite

      - name: Installation des dépendances
        run: flutter pub get

      - name: Compilation de l'APK Android
        run: flutter build apk --release --no-tree-shake-icons

      - name: Sauvegarder l'APK pour téléchargement
        uses: actions/upload-artifact@v4
        with:
          name: cantine-cpa-app
          path: build/app/outputs/flutter-apk/app-release.apk
