name: Générer l'APK Flutter

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Génération de la structure Flutter
        run: |
          mkdir -p lib
          if [ ! -f pubspec.yaml ]; then
            echo "pubspec manquant"
          fi

      - name: Compilation automatique APK
        uses: bdlukaa/flutter-build-action@v1
        with:
          target: apk
          project-root: '.'

      - name: Sauvegarder l'APK pour téléchargement
        uses: actions/upload-artifact@v4
        with:
          name: cantine-cpa-app
          path: build/app/outputs/flutter-apk/app-release.apk
